dim_opacity 1

background_image path/image.jpg

background_image_layout cscaled
#background_opacity 0.6
background_blur 1
background_tint 0.1

cursor_trail 1
cursor_trail_color cyan
cursor_trail_decay 0.3 0.7
cursor_trail_start_threshold 2

enable_audio_bell no

allow_remote_control yes
listen_on unix:/tmp/kitty.sock

scrollback_pager nvim -c "setlocal nonumber nolist showtabline=0 foldcolumn=0" -c "autocmd VimEnter * normal G" -
