dim_opacity 1

#background_image /home/zb/Downloads/2B.png
#background_image /home/zb/Downloads/2B_simple.jpg
background_image /home/zb/Downloads/midnight_2B_simple.jpg
#background_image /home/zb/Downloads/nier_automata03.jpg
#background_image /home/zb/Downloads/automata_rain.jpg
#background_image /home/zb/Downloads/white-bird.jpg

background_image_layout cscaled
#background_opacity 0.6
background_blur 1
background_tint 0.1

cursor_trail 1
cursor_trail_color cyan
cursor_trail_decay 0.3 0.7
cursor_trail_start_threshold 2

enable_audio_bell no

allow_remote_control yes
listen_on unix:/tmp/kitty.sock

scrollback_pager nvim -c "setlocal nonumber nolist showtabline=0 foldcolumn=0" -c "autocmd VimEnter * normal G" -
#scrollback_pager nvim -c "autocmd VimEnter * normal G" -

# Makes the background black
map super+backspace launch off-bg
# Bring back the 2B background
map super+^ launch kitty-bg
# Bring back the white-bird background
map super+¨ launch nvim-bg

# Opens a new terminal split in the current directory
map ctrl+enter launch --type=window --cwd=current
# Opens a new terminal tab in the current directory
map ctrl+shift+d launch --type=tab --cwd=current

# Cycle through terminal windows
map kitty_mod+k next_window
map kitty_mod+j previous_window

# Setup tall window disposition (cycle between tall and grid layout)
enabled_layouts tall:bias=50;full_size=1;mirrored=true, grid
# large vertical side toggle
map ctrl+shift+PgUp layout_action mirror toggle

# window movement
map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+down move_window down
map ctrl+shift+up move_window up
 
