#!/bin/bash
set -euo pipefail

read -p "Do you want to get all the existing aws actions ? (Y/n): " yesno

getAllAwsActions () {
	# Generated by Claude
	# fetch-actions.sh: creates actions/<iam-prefix>.txt with one action name per line
	out_dir="${1:-actions}"
	index_url="https://servicereference.us-east-1.amazonaws.com/"
	mkdir -p "$out_dir"

	# Index: array of {service, url}. Verify with: curl -s "$index_url" | jq '.[0]'
	curl -fsS "$index_url" | jq -r '.[].url' | while read -r url; do
		json=$(curl -fsS "$url")
		prefix=$(jq -r '.Name' <<< "$json" | tr '[:upper:]' '[:lower:]')   # real IAM prefix, e.g. "s3", "monitoring"->"cloudwatch"
		jq -r '.Actions[].Name' <<< "$json" | sort -u > "$out_dir/$prefix.txt"
		echo "$prefix: $(wc -l < "$out_dir/$prefix.txt") actions"
	done
}


if [[ -z $yesno || "$yesno" =~ ^[yY]$ ]]; then
	getAllAwsActions
	cd actions && counter=0 && for file in *; do counter=$(($counter+$(cat $file | wc -l))); done && echo There are [$counter] actions that exist. && cd ..
fi

echo -e "\e[1;32mwazaaa"

